Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "datalake-vm"
  # config.vm.network "private_network", type: "dhcp"
  config.vm.network "private_network", ip: "192.168.56.10"
  config.vm.network "forwarded_port", guest: 9870, host: 9870 
  config.vm.network "forwarded_port", guest: 9864, host: 9864
  config.vm.network "forwarded_port", guest: 8088, host: 8088
  config.vm.network "forwarded_port", guest: 8042, host: 8042
  config.vm.network "forwarded_port", guest: 10000, host: 10000 # Hive
  config.vm.network "forwarded_port", guest: 5000, host: 5000   # API
  if Vagrant::Util::Platform.windows?
    config.vm.synced_folder "F:/MBDS/STAGE/PROJECT/data_lake_final/projet/code-source", "/home/vagrant/datalake-final"
  else
    config.vm.synced_folder "~/datalake-final", "/home/vagrant/datalake-final"
  end
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "8192"
    vb.cpus = 4
  end

  # Provisioning automatique : Java 8 + Hadoop 3.3.6 + Hive 3.1.3 + Spark 3.4.2
  config.vm.provision "shell", path: "bootstrap.sh"
end
